/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import base_de_datos.conexion;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author Andresf13
 */
public class agendamiento_citas extends javax.swing.JFrame {

    private TableRowSorter trsfiltro;
    String filtro;

    public Connection con;

    /**
     * Creates new form agendamiento_citas
     */
    /* public static final String driver="com.mysql.jbdc.Driver";
    public static final String user="root";
    public static final String pass ="";
    public static final String url="jbdc:mysql://localhost:3306/bd_pacientes_agendados";
     */
 /* public void conector(){
        con =null;
        try{
            Class.forName(driver);
            con=(Connection)DriverManager.getConnection(url,user,pass);
            if(con!=null){
                jlabel_ce.setText("Conexion extablecida");
            }
        }catch(ClassNotFoundException | SQLException e){
            jlabel_ce.setText("Error de conexion"+e);
        }
    }*/
    public agendamiento_citas() {
        initComponents();
        mostrar_datos("");
    }

    public void mostrar_datos(String tabla) {
        String sql = "SELECT * FROM `pacientes`" + tabla;
        Statement st;
        DefaultTableModel model = new DefaultTableModel();
        conexion cn = new conexion("proyecto_poo");
        con = cn.conectar();
        System.out.println(sql);

        model.addColumn("Cedula");
        model.addColumn("Dia");
        model.addColumn("Mes");
        model.addColumn("Año");
        model.addColumn("Hora");
        model.addColumn("Doctor");
        model.addColumn("Area Medica");
        jtable_datos.setModel(model);

        String[] datos = new String[7];

        try {

            st = con.createStatement();

            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                model.addRow(datos);
            }
            jtable_datos.setModel(model);
        } catch (SQLException ex) {
            //Logger.getLogger(agendamiento_citas.class.getName()).log(Level.SEVERE, null, ex);
            java.util.logging.Logger.getLogger(agendamiento_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_titulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel_izquierdo = new javax.swing.JPanel();
        jlabel_titulo2 = new javax.swing.JLabel();
        jtext_cedula = new javax.swing.JTextField();
        jbuton_agregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbuton_atras = new javax.swing.JButton();
        jlabel_ce = new javax.swing.JLabel();
        jcombo_areaMedica = new javax.swing.JComboBox<>();
        jcombo_doctores = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtext_dia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtext_mes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtext_año = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtext_hora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_datos = new javax.swing.JTable();
        jButton_limpiar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jText_buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_titulo.setBackground(new java.awt.Color(0, 51, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AGENDAR CITAS");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloLayout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(panel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        panel_izquierdo.setBackground(new java.awt.Color(51, 204, 255));

        jlabel_titulo2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jlabel_titulo2.setText("NUEVO PACIENTE");

        jbuton_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jbuton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuton_agregarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Cedula");

        jbuton_atras.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jbuton_atras.setText("Atras");
        jbuton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuton_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_izquierdoLayout = new javax.swing.GroupLayout(panel_izquierdo);
        panel_izquierdo.setLayout(panel_izquierdoLayout);
        panel_izquierdoLayout.setHorizontalGroup(
            panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izquierdoLayout.createSequentialGroup()
                .addGroup(panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_izquierdoLayout.createSequentialGroup()
                        .addGroup(panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_izquierdoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_izquierdoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jtext_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_izquierdoLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jbuton_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_izquierdoLayout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jbuton_atras)))
                            .addGroup(panel_izquierdoLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jlabel_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addComponent(jlabel_ce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_izquierdoLayout.setVerticalGroup(
            panel_izquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izquierdoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlabel_titulo2)
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtext_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbuton_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jbuton_atras)
                .addGap(43, 43, 43)
                .addComponent(jlabel_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        getContentPane().add(panel_izquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 47, 220, 430));

        jcombo_areaMedica.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jcombo_areaMedica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AREA MEDICA", "Medicina General", "Odontologia", "Citologia" }));
        getContentPane().add(jcombo_areaMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 140, -1));

        jcombo_doctores.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jcombo_doctores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELEGIR DOCTOR", "Dr Angel Castillo", "Dr Andres Santiago ", "Dr Edwin Santiago", "Dr Jesus Gamero" }));
        getContentPane().add(jcombo_doctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Dia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 31, -1));
        getContentPane().add(jtext_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 101, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Mes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 37, -1));
        getContentPane().add(jtext_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 101, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setText("Año");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 37, -1));
        getContentPane().add(jtext_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 101, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("Hora");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 37, -1));
        getContentPane().add(jtext_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 101, -1));

        jtable_datos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jtable_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Dia", "Mes", "Año", "Hora", "Doctor", "Area Medica"
            }
        ));
        jScrollPane1.setViewportView(jtable_datos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 590, 180));

        jButton_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-broom-with-a-lot-of-dust-32.png"))); // NOI18N
        jButton_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_limpiarMouseClicked(evt);
            }
        });
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 60, 40));

        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        jButton_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_eliminarMouseClicked(evt);
            }
        });
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 60, 40));

        jText_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jText_buscarKeyReleased(evt);
            }
        });
        getContentPane().add(jText_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 140, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbuton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuton_agregarActionPerformed

        String cedula = jtext_cedula.getText();
        String dia = jtext_dia.getText();
        String mes = jtext_mes.getText();
        String año = jtext_año.getText();
        String hora = jtext_hora.getText();
        String am = jcombo_areaMedica.getSelectedItem().toString();
        String doctor = jcombo_doctores.getSelectedItem().toString();

        conexion conector = new conexion("proyecto_poo");
        Connection p = conector.conectar();
        try {
            String queri = "INSERT INTO `pacientes`(`Cedula`, `Dia`, `Mes`, `Año`, `Hora`, `Doctor`, `Area Medica`) VALUES ('" + cedula + "','" + dia + "','" + mes + "','" + año + "','" + hora + "','" + doctor + "','" + am + "')";
            PreparedStatement ps = p.prepareStatement(queri);
            ps.executeUpdate(queri);
            mostrar_datos("paciente");
        } catch (SQLException e) {

        }

    }//GEN-LAST:event_jbuton_agregarActionPerformed

    private void jbuton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuton_atrasActionPerformed
        Interfaz_medico im = new Interfaz_medico();
        im.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbuton_atrasActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jButton_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_limpiarMouseClicked
        jtext_cedula.setText(null);
        jtext_dia.setText(null);
        jtext_mes.setText(null);
        jtext_año.setText(null);
        jtext_hora.setText(null);
    }//GEN-LAST:event_jButton_limpiarMouseClicked

    private void jButton_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_eliminarMouseClicked
        int x[] = jtable_datos.getSelectedRows();
        if (x.length > 0) {
            DefaultTableModel modelo = (DefaultTableModel) jtable_datos.getModel();
            for (int i = x.length - 1; i >= 0; i--) {
                modelo.removeRow(x[i]);
            }
        }
    }//GEN-LAST:event_jButton_eliminarMouseClicked

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        conexion cn = new conexion("proyecto_poo");
        con = cn.conectar();
        int fila = jtable_datos.getSelectedRow();
        String valor = jtable_datos.getValueAt(fila, 0).toString();
        String query = "DELETE FROM `pacientes` WHERE cedula='" + valor + "'";

        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.executeUpdate();
            mostrar_datos("");

        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(agendamiento_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se puedo eliminar del registro");
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed
    
    private void jText_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_buscarKeyReleased
        mostrar_datos(jText_buscar.getText());
    }//GEN-LAST:event_jText_buscarKeyReleased

    public void filtro() {
        filtro = jtext_cedula.getText();
        trsfiltro.setRowFilter(RowFilter.regexFilter(jText_buscar.getText(), 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agendamiento_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agendamiento_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agendamiento_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agendamiento_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agendamiento_citas().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jText_buscar;
    private javax.swing.JButton jbuton_agregar;
    private javax.swing.JButton jbuton_atras;
    private javax.swing.JComboBox<String> jcombo_areaMedica;
    private javax.swing.JComboBox<String> jcombo_doctores;
    private javax.swing.JLabel jlabel_ce;
    private javax.swing.JLabel jlabel_titulo2;
    private javax.swing.JTable jtable_datos;
    private javax.swing.JTextField jtext_año;
    private javax.swing.JTextField jtext_cedula;
    private javax.swing.JTextField jtext_dia;
    private javax.swing.JTextField jtext_hora;
    private javax.swing.JTextField jtext_mes;
    private javax.swing.JPanel panel_izquierdo;
    private javax.swing.JPanel panel_titulo;
    // End of variables declaration//GEN-END:variables
}
